[workspace]
members = [
    "src/libkrun",
    "src/krun_input",
    "src/krun",
    "examples/rust_vm",
]
default-members = ["src/libkrun", "src/krun_input", "src/krun", "examples/rust_vm"]
exclude = ["examples/gtk_display"]
resolver = "2"

[profile.dev]
#panic = "abort"

[profile.release]
#panic = "abort"
lto = true

# Remove this patch once vm-memory exposes the Windows NUMA-aware mapping constructor in a release.
[patch.crates-io]
vm-memory = { git = "https://github.com/superradcompany/vm-memory.git", rev = "d0275cbcd968cef46d30299fde61a891d92fc43b" }
