use std::cmp;
use std::io::Write;
use std::sync::{Arc, Condvar, Mutex};
use std::time::{Duration, Instant};

use utils::eventfd::EventFd;
use vm_memory::{ByteValued, GuestMemoryMmap};

use super::super::{
    ActivateError, ActivateResult, DeviceQueue, DeviceState, QueueConfig, VirtioDevice,
    VirtioStateError,
};
use super::{defs, defs::uapi, GenerationDeviceError};
use crate::virtio::InterruptTransport;

const BASE_AVAIL_FEATURES: u64 = 1 << uapi::VIRTIO_F_VERSION_1 as u64;
const CONFIG_DRIVER_STATUS_OFFSET: u64 = 4;
const CONFIG_PROCESSED_SEQUENCE_LOW_OFFSET: u64 = 32;
const CONFIG_PROCESSED_SEQUENCE_HIGH_OFFSET: u64 = 36;
const CONFIG_PROCESSED_ID_OFFSET: u64 = 40;
const CONFIG_WORD_SIZE: usize = 4;
const DRIVER_STATUS_READY: u32 = 1;
const DRIVER_STATUS_ERROR: u32 = 2;

/// A VM generation identifier mixed into the guest kernel CRNG after clone or rollback.
#[derive(Clone, Copy, Debug, Default, Eq, PartialEq)]
pub struct GenerationId([u8; 16]);

impl GenerationId {
    /// Construct an identifier from exactly 16 caller-generated bytes.
    pub const fn new(bytes: [u8; 16]) -> Self {
        Self(bytes)
    }

    /// Return the identifier bytes.
    pub const fn as_bytes(&self) -> &[u8; 16] {
        &self.0
    }
}

impl From<[u8; 16]> for GenerationId {
    fn from(value: [u8; 16]) -> Self {
        Self::new(value)
    }
}

/// Point-in-time view of the VM-generation request and guest acknowledgement.
#[derive(Clone, Copy, Debug, Default, Eq, PartialEq)]
pub struct GenerationStateSnapshot {
    /// Whether the bundled guest driver has completed probing.
    pub driver_ready: bool,

    /// Whether the guest driver rejected the device protocol.
    pub driver_error: bool,

    /// Sequence of the request currently published by the host.
    pub request_sequence: u64,

    /// Identifier currently published by the host.
    pub requested_id: GenerationId,

    /// Sequence last reported as processed by the guest kernel.
    pub processed_sequence: u64,

    /// Identifier last reported as processed by the guest kernel.
    pub processed_id: GenerationId,
}

/// Result of waiting for one exact generation request.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum GenerationWaitOutcome {
    /// The guest kernel processed the requested generation.
    Processed,

    /// A newer request replaced the one being waited on.
    Superseded,

    /// The deadline elapsed before the exact request was acknowledged.
    TimedOut,
}

#[derive(Clone, Copy, Debug, Default)]
#[repr(C)]
struct VirtioGenerationConfig {
    version: u32,
    driver_status: u32,
    request_sequence_low: u32,
    request_sequence_high: u32,
    generation_id: [u32; 4],
    processed_sequence_low: u32,
    processed_sequence_high: u32,
    processed_id: [u32; 4],
}

// Safe because every field is a u32 and the C layout therefore has no implicit padding.
unsafe impl ByteValued for VirtioGenerationConfig {}

#[derive(Default)]
struct GenerationObservation {
    state: GenerationStateSnapshot,
}

#[derive(Default)]
struct GenerationTracker {
    observation: Mutex<GenerationObservation>,
    changed: Condvar,
}

/// Cloneable event-driven wait surface independent of the device mutex.
///
/// Waiting through this handle is important: guest config writes take the device mutex before
/// publishing their acknowledgement, so a waiter must never retain that mutex while sleeping.
#[derive(Clone)]
pub struct GenerationProcessingHandle {
    tracker: Arc<GenerationTracker>,
}

pub struct Generation {
    pub(crate) queues: Option<Vec<DeviceQueue>>,
    pub(crate) activate_evt: EventFd,
    avail_features: u64,
    acked_features: u64,
    device_state: DeviceState,
    config: VirtioGenerationConfig,
    tracker: Arc<GenerationTracker>,
}

impl Generation {
    /// Create the private VM-generation device with no pending fork/rollback request.
    pub fn new() -> super::Result<Self> {
        let config = VirtioGenerationConfig {
            version: 1,
            ..Default::default()
        };
        let tracker = Arc::new(GenerationTracker::default());

        Ok(Self {
            queues: None,
            activate_evt: EventFd::new(utils::eventfd::EFD_NONBLOCK)
                .map_err(GenerationDeviceError::EventFd)?,
            avail_features: BASE_AVAIL_FEATURES,
            acked_features: 0,
            device_state: DeviceState::Inactive,
            config,
            tracker,
        })
    }

    pub fn id(&self) -> &str {
        defs::VMGENID_DEV_ID
    }

    /// Publish a new generation and notify an active guest driver.
    ///
    /// The caller supplies the identifier from its operating-system CSPRNG. The returned sequence
    /// identifies this request when waiting for the guest kernel acknowledgement.
    pub fn install(&mut self, id: GenerationId) -> Option<u64> {
        // A retry of one restore attempt reuses both its persisted identifier and its device-local
        // sequence. Re-signal it instead of manufacturing a second logical request or reseeding
        // the guest twice with the same attempt value.
        if self.request_sequence() != 0 && words_to_id(self.config.generation_id) == id {
            if let DeviceState::Activated(_, ref interrupt) = self.device_state {
                interrupt.signal_config_change();
            }
            return Some(self.request_sequence());
        }

        let sequence = self.request_sequence().checked_add(1)?;
        let [low, high] = split_sequence(sequence);
        self.config.generation_id = id_to_words(id);
        self.config.request_sequence_high = high;
        self.config.request_sequence_low = low;
        self.publish_observation();

        if let DeviceState::Activated(_, ref interrupt) = self.device_state {
            interrupt.signal_config_change();
        }
        Some(sequence)
    }

    /// Return the latest host request and guest acknowledgement.
    pub fn state_snapshot(&self) -> GenerationStateSnapshot {
        self.tracker.observation.lock().unwrap().state
    }

    /// Return a handle that can wait without retaining the virtio device mutex.
    pub fn processing_handle(&self) -> GenerationProcessingHandle {
        GenerationProcessingHandle {
            tracker: self.tracker.clone(),
        }
    }

    fn request_sequence(&self) -> u64 {
        join_sequence(
            self.config.request_sequence_low,
            self.config.request_sequence_high,
        )
    }

    fn publish_observation(&self) {
        let state = GenerationStateSnapshot {
            driver_ready: self.config.driver_status & DRIVER_STATUS_READY != 0,
            driver_error: self.config.driver_status & DRIVER_STATUS_ERROR != 0,
            request_sequence: self.request_sequence(),
            requested_id: words_to_id(self.config.generation_id),
            processed_sequence: join_sequence(
                self.config.processed_sequence_low,
                self.config.processed_sequence_high,
            ),
            processed_id: words_to_id(self.config.processed_id),
        };
        let mut observation = self.tracker.observation.lock().unwrap();
        observation.state = state;
        self.tracker.changed.notify_all();
    }

    fn apply_guest_word(&mut self, offset: u64, word: u32) -> bool {
        match offset {
            CONFIG_DRIVER_STATUS_OFFSET => self.config.driver_status = word,
            CONFIG_PROCESSED_SEQUENCE_LOW_OFFSET => self.config.processed_sequence_low = word,
            CONFIG_PROCESSED_SEQUENCE_HIGH_OFFSET => self.config.processed_sequence_high = word,
            offset
                if (CONFIG_PROCESSED_ID_OFFSET..CONFIG_PROCESSED_ID_OFFSET + 16)
                    .contains(&offset)
                    && offset.is_multiple_of(CONFIG_WORD_SIZE as u64) =>
            {
                self.config.processed_id
                    [((offset - CONFIG_PROCESSED_ID_OFFSET) / CONFIG_WORD_SIZE as u64) as usize] =
                    word;
            }
            _ => return false,
        }
        true
    }
}

impl GenerationProcessingHandle {
    /// Wait until the guest processes one exact request or the deadline expires.
    pub fn wait_processed(
        &self,
        sequence: u64,
        id: GenerationId,
        timeout: Duration,
    ) -> GenerationWaitOutcome {
        let deadline = Instant::now() + timeout;
        let mut observation = self.tracker.observation.lock().unwrap();

        loop {
            let state = observation.state;
            if state.request_sequence != sequence || state.requested_id != id {
                return GenerationWaitOutcome::Superseded;
            }
            if state.processed_sequence == sequence && state.processed_id == id {
                return GenerationWaitOutcome::Processed;
            }

            let now = Instant::now();
            if now >= deadline {
                return GenerationWaitOutcome::TimedOut;
            }
            let (next, result) = self
                .tracker
                .changed
                .wait_timeout(observation, deadline - now)
                .unwrap();
            observation = next;
            if result.timed_out()
                && !(observation.state.processed_sequence == sequence
                    && observation.state.processed_id == id)
            {
                return GenerationWaitOutcome::TimedOut;
            }
        }
    }
}

impl VirtioDevice for Generation {
    fn avail_features(&self) -> u64 {
        self.avail_features
    }

    fn acked_features(&self) -> u64 {
        self.acked_features
    }

    fn set_acked_features(&mut self, acked_features: u64) {
        self.acked_features = acked_features;
    }

    fn device_type(&self) -> u32 {
        uapi::VIRTIO_ID_MSB_VMGENID
    }

    fn device_name(&self) -> &str {
        "msb-vmgenid"
    }

    fn queue_config(&self) -> &[QueueConfig] {
        &defs::QUEUE_CONFIG
    }

    fn read_config(&self, offset: u64, mut data: &mut [u8]) {
        let config = self.config.as_slice();
        let config_len = config.len() as u64;
        if offset >= config_len {
            error!("virtio-msb-vmgenid: failed to read config space");
            return;
        }
        if let Some(end) = offset.checked_add(data.len() as u64) {
            data.write_all(&config[offset as usize..cmp::min(end, config_len) as usize])
                .unwrap();
        }
    }

    fn write_config(&mut self, offset: u64, data: &[u8]) {
        if data.len() == CONFIG_WORD_SIZE {
            let word = u32::from_le_bytes(data.try_into().unwrap());
            if self.apply_guest_word(offset, word) {
                self.publish_observation();
                return;
            }
        }

        warn!(
            "virtio-msb-vmgenid: rejected guest config write (offset={offset:x}, len={:x})",
            data.len()
        );
    }

    fn activate(
        &mut self,
        mem: GuestMemoryMmap,
        interrupt: InterruptTransport,
        queues: Vec<DeviceQueue>,
    ) -> ActivateResult {
        if queues.len() != defs::NUM_QUEUES {
            error!(
                "Cannot perform activate. Expected {} queue(s), got {}",
                defs::NUM_QUEUES,
                queues.len()
            );
            return Err(ActivateError::BadActivate);
        }
        if self.activate_evt.write(1).is_err() {
            error!("Cannot write to activate_evt");
            return Err(ActivateError::BadActivate);
        }

        self.queues = Some(queues);
        self.device_state = DeviceState::Activated(mem, interrupt);
        if self.request_sequence()
            != join_sequence(
                self.config.processed_sequence_low,
                self.config.processed_sequence_high,
            )
        {
            // Restored guests do not reprobe an already-bound driver. Arm the config interrupt as
            // part of activation so a request installed while the backend was inert is not lost.
            if let DeviceState::Activated(_, ref interrupt) = self.device_state {
                interrupt.signal_config_change();
            }
        }
        Ok(())
    }

    fn is_activated(&self) -> bool {
        self.device_state.is_activated()
    }

    fn reset(&mut self) -> bool {
        self.queues = None;
        self.device_state = DeviceState::Inactive;
        true
    }

    fn supports_quiesce(&self) -> bool {
        true
    }

    fn quiesce(&mut self) -> Result<Vec<DeviceQueue>, VirtioStateError> {
        if !self.device_state.is_activated() {
            return Err(VirtioStateError::InvalidLifecycle(
                "msb-vmgenid must be activated before quiescence",
            ));
        }
        let queues = self
            .queues
            .take()
            .ok_or(VirtioStateError::InvalidLifecycle(
                "msb-vmgenid is activated without queues",
            ))?;
        self.device_state = DeviceState::Inactive;
        Ok(queues)
    }
}

fn split_sequence(sequence: u64) -> [u32; 2] {
    [sequence as u32, (sequence >> 32) as u32]
}

fn join_sequence(low: u32, high: u32) -> u64 {
    u64::from(low) | (u64::from(high) << 32)
}

fn id_to_words(id: GenerationId) -> [u32; 4] {
    let bytes = id.0;
    [
        u32::from_le_bytes(bytes[0..4].try_into().unwrap()),
        u32::from_le_bytes(bytes[4..8].try_into().unwrap()),
        u32::from_le_bytes(bytes[8..12].try_into().unwrap()),
        u32::from_le_bytes(bytes[12..16].try_into().unwrap()),
    ]
}

fn words_to_id(words: [u32; 4]) -> GenerationId {
    let mut bytes = [0_u8; 16];
    for (index, word) in words.into_iter().enumerate() {
        bytes[index * 4..index * 4 + 4].copy_from_slice(&word.to_le_bytes());
    }
    GenerationId(bytes)
}

#[cfg(test)]
mod tests {
    use std::sync::mpsc;
    use std::thread;

    use super::*;

    fn id(byte: u8) -> GenerationId {
        GenerationId::new([byte; 16])
    }

    fn acknowledge(device: &mut Generation, sequence: u64, generation: GenerationId) {
        for (index, word) in id_to_words(generation).into_iter().enumerate() {
            device.write_config(
                CONFIG_PROCESSED_ID_OFFSET + (index * CONFIG_WORD_SIZE) as u64,
                &word.to_le_bytes(),
            );
        }
        let [low, high] = split_sequence(sequence);
        device.write_config(CONFIG_PROCESSED_SEQUENCE_HIGH_OFFSET, &high.to_le_bytes());
        device.write_config(CONFIG_PROCESSED_SEQUENCE_LOW_OFFSET, &low.to_le_bytes());
    }

    #[test]
    fn install_publishes_monotonic_requests() {
        let mut device = Generation::new().unwrap();

        assert_eq!(device.install(id(1)), Some(1));
        assert_eq!(device.install(id(2)), Some(2));
        assert_eq!(device.state_snapshot().requested_id, id(2));
    }

    #[test]
    fn retrying_same_attempt_reuses_sequence() {
        let mut device = Generation::new().unwrap();

        let first = device.install(id(2)).unwrap();
        let retry = device.install(id(2)).unwrap();

        assert_eq!(retry, first);
    }

    #[test]
    fn exact_acknowledgement_completes_wait() {
        let mut device = Generation::new().unwrap();
        let sequence = device.install(id(3)).unwrap();
        acknowledge(&mut device, sequence, id(3));

        assert_eq!(
            device
                .processing_handle()
                .wait_processed(sequence, id(3), Duration::ZERO),
            GenerationWaitOutcome::Processed
        );
    }

    #[test]
    fn stale_acknowledgement_does_not_complete_new_request() {
        let mut device = Generation::new().unwrap();
        let old_sequence = device.install(id(4)).unwrap();
        acknowledge(&mut device, old_sequence, id(4));
        let current_sequence = device.install(id(5)).unwrap();

        assert_eq!(
            device
                .processing_handle()
                .wait_processed(current_sequence, id(5), Duration::ZERO),
            GenerationWaitOutcome::TimedOut
        );
    }

    #[test]
    fn replaced_request_is_reported_as_superseded() {
        let mut device = Generation::new().unwrap();
        let old_sequence = device.install(id(6)).unwrap();
        device.install(id(7)).unwrap();

        assert_eq!(
            device
                .processing_handle()
                .wait_processed(old_sequence, id(6), Duration::ZERO),
            GenerationWaitOutcome::Superseded
        );
    }

    #[test]
    fn processed_old_request_is_still_superseded_by_new_request() {
        let mut device = Generation::new().unwrap();
        let old_sequence = device.install(id(6)).unwrap();
        acknowledge(&mut device, old_sequence, id(6));
        device.install(id(7)).unwrap();

        assert_eq!(
            device
                .processing_handle()
                .wait_processed(old_sequence, id(6), Duration::ZERO),
            GenerationWaitOutcome::Superseded
        );
    }

    #[test]
    fn guest_cannot_overwrite_host_request_fields() {
        let mut device = Generation::new().unwrap();
        let sequence = device.install(id(8)).unwrap();

        device.write_config(8, &99_u32.to_le_bytes());

        assert_eq!(device.state_snapshot().request_sequence, sequence);
        assert_eq!(device.state_snapshot().requested_id, id(8));
    }

    #[test]
    fn waiter_wakes_after_guest_acknowledgement_without_device_lock() {
        let mut device = Generation::new().unwrap();
        let sequence = device.install(id(9)).unwrap();
        let processing = device.processing_handle();
        let (started_tx, started_rx) = mpsc::channel();

        let waiter = thread::spawn(move || {
            started_tx.send(()).unwrap();
            processing.wait_processed(sequence, id(9), Duration::from_secs(1))
        });
        started_rx.recv().unwrap();
        acknowledge(&mut device, sequence, id(9));

        assert_eq!(waiter.join().unwrap(), GenerationWaitOutcome::Processed);
    }
}
